### ISSUE TITLE
Wrong Cseq on ACK during race with re-Invite

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1071]
I believe this is related to issue #1034

If a re-Invite is received at the same time as the ACK for the initial call setup the ACK gets forwarded with the Cseq of the re-Invite and not the initial Invite. Since the ACK has the wrong Cseq it may cause the call to be dropped/ended, so it is a big inter-op issue.

I haven't seen this affects overlapping requests later in the dialog, but I am not 100% sure it doesn't.

Seems like there may be some underlying Cseq management issues in the dialog module. I don't see (at least, haven't caught) this issue on my 1.11 systems, just 2.2.

Attached is an example capture.

[Overlap_Invite_ACK_Cseq.zip](https://github.com/OpenSIPS/opensips/files/831929/Overlap_Invite_ACK_Cseq.zip)

Opensips Version:
version: opensips 2.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 52813f4
main.c compiled on 16:33:40 Mar  7 2017 with gcc 5.2.1

**Comment by rrb3942** [comment]
Further testing shows this only happens when pinging is enabled on the dialog, removing that flag stops opensips from attempting to rewrite the cseq.

**Comment by razvancrainea** [comment]
Can you check if this is still happening after fixing Issue #1008?

**Comment by rrb3942** [comment]
Sorry for the delay, didn't notice this ticket had been updated.

Some testing shows #1008 may have fixed it, but in all honesty it is very difficult to trigger this issue for testing.

**Comment by rrb3942** [comment]
No problems to report since #1008

**Comment by rrb3942** [comment]
Was doing some testing and found that this happens with any re-Invite if dialog pinging (we are using OPTION pings) is enabled.

version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3dab829
main.c compiled on 16:03:55 Dec 17 2018 with gcc 7

Capture:
[ReInvite_ACK_Race_Cseq.zip](https://github.com/OpenSIPS/opensips/files/2691772/ReInvite_ACK_Race_Cseq.zip)

In this example calls come in the .40 interface and leave on the .41 interface. We also have topology hiding enabled, but I don't think that should affect this case. If you jump to Cseq 112 and 113 you can see the behaviour. I have found that adding a slight usleep of 100ms when receiving the ACK helps to trigger the issue.

Do you know when the update to the Cseq in the dialog happens at the script level? Is it at the topology_hiding_match() or when the transaction is created (t_newtran/t_relay)? Just trying to figure out if there is something I can do at script level to help avoid this.

It seems like any kind of overlapping request might be a problem for how the dialog module currently handles cseq if pinging is enabled, but I am not sure of a good way to resolve it.

**Comment by rrb3942** [comment]
I'll just update that I saw this under 2.4.x still when we updated out systems. My very kludge of a work around is to add a very small usleep() to non-ACK methods with a totag before further processing to help avoid the race. This helps in the common case of an immediate reINVITE after a 200OK where the INVITE and ACK reach the proxy at nearly identical times.

**Comment by dsandras** [comment]
@bogdan-iancu I confirm that bug is still present in 3.2 and was not present in 1.8.x. When there is a reINVITE and an ACK processed at the same time by opensips, the ACK relayed by opensips will use the same CSEQ than the reINVITE depending on the processing order.

**Comment by razvancrainea** [comment]
I am trying to create a patch where we will be using some mappings between INVITEs and their ACKs. Is it possible for you to test it and see if it fixes your problem?

Best regards,
Razvan

**Comment by razvancrainea** [comment]
Hi, @dsandras ! I've just pushed in the master branch a patch for this issue - it currently keep a mapping between all INVITEs CSeqs, so it can restore them properly when the ACK is received. The current implementation is limited to 10 entries, but if you can confirm everything works for for you, I can extend the patch to make the limit configurable.
Thanks and let me know when you get a chance to test!

**Comment by dsandras** [comment]
Hi @razvancrainea , thanks a lot, I will test next week and get back to you but it looks good!

**Comment by fbinet** [comment]
Was this ever patched inside the 3.2 branch or I would have to update to 3.3 ?

Thank you

**Comment by ankogan** [comment]
> Was this ever patched inside the 3.2 branch or I would have to update to 3.3 ?
It looks like the issue is not fixed for 3.2. I've got it on 3.2.9

**Comment by razvancrainea** [comment]
I was waiting for @dsandras for confirmation that it works, before backporting it. Moreover, the patch is not 100%, as it has a hardcoded limit, which is not 100% correct - but I was waiting for a confirmation it solves the problem, before investing more time in completing the job.
@fbinet, @ankogan, if you could backport the 80ff319 commit to 3.2 so you can test and confirm yourself, that might work as well.

**Comment by dsandras** [comment]
Hi everyone,

Unfortunately, it was very hard to reproduce and I could never find the
time...
> Message ID: ***@***.***>
Sorry about that, but I'm interested in the result.


-- 
Damien Sandras ***@***.***>

**Comment by ankogan** [comment]
Hi, 
Unfortunately, the issue was only on a huge clients trafic, and I have no possibility to test it there. But I think it can be easily reproduced by sipp...
