### ISSUE TITLE
Crashing in mid-registrar on reply retransmission

### ISSUE THREAD

**Issue by attermann** [OpenSIPS/opensips#1184]
I am running the latest 2.3 with mid-registrar in AOR-throttle mode. Crashes are occurring regularly in save_restore_req_contacts() called from the transaction callback when a retransmission of a reply is received.  I have narrowed the issue down to corruption in memory when enumerating contacts from the original request.  It seems that some part of the parsed headers in the original request may be getting freed.  Is it possible that this happens in a REGISTER transaction after a final response is received?  Is there some callback mechanism that only gets called a single time on final-response in a transaction that could be used instead, as opposed to TMCB_RESPONSE_IN which is being used now and is called for each retransmission?  Maybe I'm barking up the wrong tree here, but considering that these crashes only happen on retransmission of final response, I am hoping that avoiding processing the retransmissions would avoid this issue entirely.

Thanks.

**Comment by liviuchircu** [comment]
I completely overlooked retransmissions during development. Managed to get it to crash as soon as I set up this scenario - currently working on it.

**Comment by liviuchircu** [comment]
Fix available in f522b0ef089. Since I'm still exploring this new dimension of a slow main registrar, can you please also confirm it works before we merge it into `2.3`? Many thanks!

**Comment by attermann** [comment]
Hi Liviu.  Thanks for the quick response!  I will test this today and get back to you with my results.

Chad.

**Comment by attermann** [comment]
@liviuchircu Your fix has passed my sipp tests that triggered the crash, so it looks like it will work.  If you can merge it into `2.3` that would be great.

Note that I have a couple of other fixes that address memory corruption issues related to the mri in shared memory.  Your fix above resolves one of them where the mri was being freed multiple times on retransmission, but my fix moves the free operation to the TMCB_TRANS_DELETED callback.  I will be submitting a pull request for these fixes shortly and will let you know since they are related to this and another issue I submitted recently.

**Comment by attermann** [comment]
@liviuchircu Sorry I spoke too soon.  The issue is still there.  Looking at logs, it appears that retransmissions are coming in nearly concurrently on multiple processes, so each process is seeing the mri pointer in `params->param` before the process that is handling the first reply has a chance to set it to NULL.  Granted my sipp test is sending retransmission in immediate succession which generally won't be the case in the real-world, but it certainly will eventually happen in a congested network.

**Comment by attermann** [comment]
FYI, #1187 has the other fixes for memory corruption that I was referring to above.

**Comment by liviuchircu** [comment]
You are right, the `NULL` fix won't hold - I even checked the tm code to see if the callbacks are mutually exclusive, but wrongly did so. If we take a look at `modules/tm/t_lookup.c +843`, where the `TMCB_RESPONSE_IN` is called, it would appear that `run_trans_callbacks()` is lock guarded. However, once the transaction is found, there lock is released right before the callbacks are run, so we'd have to add some mid_registrar-level locking if we want to make it work.

The question is: how should it work on a 200 OK + retransmit? Either "save/skip" or "save/update"? The former one makes more sense to me. From a coding pov, until we enhance the tm API, I prefer the `TMCB_TRANS_DELETED` solution. I will test it myself a bit today, and proceed to merge it.

**Comment by liviuchircu** [comment]
Pushed an additional fix (496e2dcc2) which adds some much needed locking. All good on my tests - please let me know if it works on your sipp setup as well.
