### ISSUE TITLE
[BUG] SIPREC 100% CPU

### ISSUE THREAD

**Issue by timurkir** [OpenSIPS/opensips#2745]
**OpenSIPS version you are running**

```
version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:33:16 Aug 19 2021 with gcc 4.8.5
```

**Describe the bug**

The main sip dialog ended with code 480 before receiving 200ok from SRS,
after which an entry appeared in the log and the load of one cpu core is constantly 100%.

100% CPU problem process:
"load:load-proc-6": 100,
"load:load1m-proc-6": 100,
"load:load10m-proc-6": 100,
"load:load-proc-50": 100,
"load:load1m-proc-50": 100,
"load:load10m-proc-50": 100,
where
sipproxy process
         {
            "ID": 6,
            "PID": 41603,
            "Type": "SIP receiver udp:10.2.30.105:5060"
        },
siprec trunk to SRS process
       {
            "ID": 50,
            "PID": 41647,
            "Type": "SIP receiver udp:10.2.30.108:5060"
        },

**To Reproduce**

```
SIP exchange:
(proxy+SRC) = One OpenSips server
No.     Time                          Source                Destination           Protocol    Length Info
 1    2022-02-04 02:24:35,634333    10.2.30.47          10.2.30.105(proxy)  SIP/SDP/ISUP(ITU) 1083   Request: INVITE sip:9991234567@mydomain.org;user=phone | , ISUP:IAM
 2    2022-02-04 02:24:35,639281    10.2.30.105(proxy)  10.2.30.47          SIP               427    Status: 100 Giving it a try | 
 3    2022-02-04 02:24:35,639364    10.2.30.105(proxy)  10.2.30.100         SIP/SDP/ISUP(ITU) 1285   Request: INVITE sip:9991234567@10.2.30.100;user=phone | , ISUP:IAM
 4    2022-02-04 02:24:35,639884    10.2.30.100         10.2.30.105(proxy)  SIP               517    Status: 100 trying -- your call is important to us | 
 5    2022-02-04 02:24:46,645183    10.2.30.100         10.2.30.105(proxy)  SIP/ISUP(ITU)     839    Status: 181 Call Is Being Forwarded | , ISUP:ACM
 6    2022-02-04 02:24:46,645348    10.2.30.105(proxy)  10.2.30.47          SIP/ISUP(ITU)     772    Status: 181 Call Is Being Forwarded | , ISUP:ACM
 7    2022-02-04 02:24:48,265600    10.2.30.100         10.2.30.105(proxy)  SIP/SDP/ISUP(ITU) 1201   Status: 183 Session Progress | , ISUP:CPG
 8    2022-02-04 02:24:48,266540    10.2.30.105(proxy)  10.2.30.47          SIP/SDP/ISUP(ITU) 1152   Status: 183 Session Progress | , ISUP:CPG
 9    2022-02-04 02:24:48,266684    10.2.30.108(SRC)    172.16.4.21(SRS)    SIP/SDP/XML       1262   Request: INVITE sip:172.16.4.21:5060;transport=udp | 
10    2022-02-04 02:24:48,275636    172.16.4.21(SRS)    10.2.30.108(SRC)    SIP               306    Status: 100 Trying | 
11    2022-02-04 02:24:48,325674    10.2.30.100         10.2.30.105(proxy)  SIP/ISUP(ITU)     707    Status: 480 Temporarily Unavailable | , ISUP:REL
12    2022-02-04 02:24:48,325801    10.2.30.105(proxy)  10.2.30.100         SIP               445    Request: ACK sip:9991234567@10.2.30.100;user=phone | 
13    2022-02-04 02:24:48,325856    10.2.30.105(proxy)  10.2.30.47          SIP/ISUP(ITU)     640    Status: 480 Temporarily Unavailable | , ISUP:REL
14    2022-02-04 02:24:48,326702    10.2.30.47          10.2.30.105(proxy)  SIP               423    Request: ACK sip:9991234567@mydomain.org;user=phone | 
15    2022-02-04 02:24:48,333265    172.16.4.21(SRS)    10.2.30.108(SRC)    SIP/SDP           851    Status: 200 OK (INVITE) | 
16    2022-02-04 02:24:48,333504    10.2.30.108(SRC)    172.16.4.21(SRS)    SIP               457    Request: ACK sip:172.16.4.21:5060;transport=udp | 
17    2022-02-04 02:24:48,334073    10.2.30.108(SRC)    172.16.4.21(SRS)    SIP               457    Request: BYE sip:172.16.4.21:5060;transport=udp | 
18    2022-02-04 02:24:48,398141    172.16.4.21(SRS)    10.2.30.108(SRC)    SIP               470    Status: 200 OK (BYE) | 
```

**Expected behavior**

**Relevant System Logs**

```
Feb  4 02:24:48 0000SIPREC /usr/sbin/opensips[41647]: ERROR:siprec:srec_register_callbacks: cannot register callback for dialog termination
Feb  4 02:24:48 0000SIPREC /usr/sbin/opensips[41647]: ERROR:siprec:srec_b2b_notify: cannot register callback for terminating session
Feb  4 02:24:53 0000SIPREC /usr/sbin/opensips[41608]: CRITICAL:siprec:src_unref_session: #012>>> invalid ref for session=0x7f0732bf5a40 ref=-1 (src_unref_session:148)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues 
```

**OS/environment information**
 - Operating System:  RHEL7
 - OpenSIPS installation:  yum install https://yum.opensips.org/3.2/releases/el/7/x86_64/opensips-yum-releases-3.2-6.el7.noarch.rpm
 - other relevant information:

**Additional context**

**Comment by timurkir** [comment]
Friends, if you have the same problem, then a temporary solution can be like this:
if (is_method("INVITE")) {
if (!has_totag()) {
t_newtran();
t_wait_for_new_branches(2);
create_dialog();
...
}
}
but these are not all problems - the same will happen with CANCEL from calling party number.
Oh, if you had the siprec_unforce() function available from REQUEST_ROUTE and ONREPLY_ROUTE...!???

**Comment by rroiss** [comment]
Hi, I am also facing this issue.
The temporary solution from timurkin helps, but as mentioned the same happens with the CANCEL.
So, what to do then?

**Comment by razvancrainea** [comment]
I'm trying to find some time to look into this and try to replicate. As soon as I find some time, I will keep you posted.

**Comment by timurkir** [comment]
razvancrainea:  thanks
rroiss:   as a temporary solution I did this (works if after 200 ok cancelling the called number sends 487 Request Terminated) 
route{
.....
	if (has_body("application/sdp"))  {
		if (is_method("INVITE")) {
			if (!has_totag()) {
        			t_newtran();
				t_wait_for_new_branches(2);
				create_dialog("E");
			}
                	rtpproxy_offer("roc"); 
                	t_on_reply("1");
                } else if (is_method("ACK")) {
                        rtpproxy_answer("roc");
                }
        } else {
                if (is_method("INVITE")) {
			if (!has_totag()) {
				create_dialog();
			}
                        t_on_reply("2"); 
                } else {
        		if (is_method("BYE|CANCEL")){
			        if (is_method("BYE") && !sipmsg_validate("hf")) {
					send_reply(400, "Bad Request");
					drop();
			        }
                        }
                        t_on_reply("1"); 
                }
	}
.....
}

onreply_route[1] { 
	if ( t_check_status("[3-9][0-9][0-9]") && ($DLG_status == 1) ) { t_wait_no_more_branches(); }
	if (t_check_status("487")) {
		if ($DLG_status > 1 && $DLG_status < 5) {
			async( sleep(35), after_sleep );
		}
	}
   .....
}

route[after_sleep] {
    return(1);
}

sleep(35) - in my case, SRS does not delay 200 OK for more than 35 seconds.
It is important that fr_inv_timeout does not expire faster than sleep(35) ends, otherwise the CPU usage will be 100% temporarily!
I chose these timeouts (originally fr_inv_timeout was 60): 
loadmodule "tm.so"
modparam("tm", "T1_timer", 2000)  ## 1th retransmission
modparam("tm", "fr_timeout", 5)   ## time for all retransmissions
modparam("tm", "fr_inv_timeout", 120)
.....

**Comment by rroiss** [comment]
razvancrainea, timurkir: thanks a lot!
I'll try immediately and let you know.

**Comment by rroiss** [comment]
Hello, sorry for delayed reply. 
My system was on 2.4, so I had to switch to 3.2 because of t_wait_no_more_branches.
Seems to work on this special case.
Thank you very much!

**Comment by timurkir** [comment]
Unfortunately, if SRS delays answer/200ok (in my case, up to 32 seconds), and the main sip dialog, the rtp of which should be recorded, has already completed by BYE, then an error occurs.
After several errors, opensips goes to restart ( 

Apr  15 03:59:46 SIPREC /usr/sbin/opensips[98274]: ERROR:siprec:srec_register_callbacks: cannot register callback for dialog termination
Apr  15 03:59:46 SIPREC /usr/sbin/opensips[98274]: ERROR:siprec:srec_b2b_notify: cannot register callback for terminating session
Apr  15 04:03:10 SIPREC /usr/sbin/opensips[98267]: CRITICAL:core:sig_usr: segfault in process pid: 98267, id: 17
Apr  15 04:03:10 SIPREC kernel: [10508124.517135] traps: opensips[98267] general protection ip:7f182c50dbfc sp:7ffd7df95258 error:0 in libc-2.17.so[7f182c3ce000+1c4000]
Apr  15 04:03:10 SIPREC kernel: traps: opensips[98267] general protection ip:7f182c50dbfc sp:7ffd7df95258 error:0 in libc-2.17.so[7f182c3ce000+1c4000]
Apr  15 04:03:15 SIPREC /usr/sbin/opensips[98250]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f1635c49a18), first free: (null): (null)(0) - aborting!
Apr  15 04:03:15 SIPREC systemd: opensips.service: main process exited, code=killed, status=6/ABRT
Apr  15 04:03:15 SIPREC systemd: Unit opensips.service entered failed state.
Apr  15 04:03:15 SIPREC systemd: opensips.service failed.
Apr  15 04:03:15 SIPREC systemd: opensips.service holdoff time over, scheduling restart.
Apr  15 04:03:15 SIPREC systemd: Stopped OpenSIPS is a very fast and flexible SIP (RFC3261) server.
Apr  15 04:03:15 SIPREC systemd: Starting OpenSIPS is a very fast and flexible SIP (RFC3261) server...

**Comment by nelsonm72** [comment]
I have just run into this same issue. We were able to build a scenario to easily replicate it (cancel original call leg before SIPREC leg is answered).

As soon as this happens we see an opensips thread pin at 100% CPU and processing is degraded and the begins leaking shared memory. After no more memory is left and the process stops accepting calls and will eventually crash.

This is a pretty bad issue for us, so i have implemented the work around above however it is not ideal so we would like to get it out as soon as we can.

Let me know if there is anything additional i can provide to help with this issue

**Comment by timurkir** [comment]
???

**Comment by achittanoor** [comment]
??

**Comment by razvancrainea** [comment]
Hi all!

Apologies for not getting back here earlier, but I've been involved in other projects. In the mean time I've managed to replicate this in a different scenario, but seems very similar to this one. For my specific case, 
[this patch](https://github.com/OpenSIPS/opensips/files/9281898/b2b_entities_fix_deadlock.txt) sorted out the issue.
Can you please apply it on your OpenSIPS code and let me know if it fixes your as well?

Best regards,
Răzvan

**Comment by agreen-bw** [comment]
Hi @razvancrainea,

I stumbled across this issue a while back because our team has been hitting it.  I tried your patch in my local environment and still see the behavior described by @timurkir, so doesn't seem like it fixes it for us.

I did however do some diving into the code and it seems that this patch DOES fix the issue for us:  
https://github.com/OpenSIPS/opensips/compare/3.2...agreen-bw:opensips:opensips-issue-2745

I'm pretty new to opensips, but it seems to me like that line of code :point_up: is an extra UNREF on the SIPREC session object that causes it to get cleaned up too early.  Basically what seems to happen is that when the main call-leg is CANCEL'd but the SRS sends a BYE before the main leg's transaction timer expires, the line of code above has caused the sip rec session object to have been already cleaned-up/freed and the transaction timer expiring causes src_unref_session to get called again and the process handling timers spins in circles because the session has already been cleaned up.

I can't find / think of any scenarios where this change causes other problems... but I'm very new to opensips so I'd love to get your thoughts on this.
