### ISSUE TITLE
[FEATURE] Add flag acive/backup in   set_dlg_sharing_tag() function  from script level

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2829]
Hello Everyone,
Seems like B flag is not working  in create dialog function.

Version

```
[root@aitdevossbc01 ~]# opensips -V
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 50407d340
main.c compiled on 00:00:00 Apr 20 2022 with gcc 10

```

Use case 

CSTA send INFO which contain data. If no timeout set on dialog it keep sending until dialog expires and then routing is failing 

<img width="1502" alt="Screen Shot 2022-05-04 at 9 27 30 AM" src="https://user-images.githubusercontent.com/59034879/166714248-829d9ee6-4e8b-418d-bf8a-d5cd1356bd05.png">

Configuration 

```
#### Dialog
loadmodule "dialog.so"
modparam("dialog", "db_url", "")
modparam("dialog", "db_mode", 3)
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 3600)
modparam("dialog", "options_ping_interval", 900)
modparam("dialog", "profiles_with_value", "caller ; domain")
modparam("dialog", "dialog_replication_cluster", 1)
```

```
        # CSTA INVITE
        if(!has_totag() && is_method("INVITE") && has_body("application/csta+xml")) {
                if(sstCheckMin(1)) {
                        xlog("[REQ_ROUTE] [$rm] 422 Session Timer Too Small reply sent.\n");
                        exit;
                }
                # Track the session timers via the dialog module
                setflag("SST_FLAG");
                # Send BYE on dialog timeout
                create_dialog("B");
                # Dialog lifetime
                $DLG_timeout = 3600;
                topology_hiding("U");
                #xlog("[REQ_ROUTE] [$rm] CSTA reqest from => [$socket_in(ip)]\n");
        }
```

Issue

I don't see any BYE originated from opensips where are "B" flag is specified in create dialog function. End point keep sending INFO and opensips tries reply 481.  Session is not closed properly and connection is opened.

Expectation  

On dialog timeout I should see BYE send by opensips to each leg of the call.

**Comment by volga629-1** [comment]
I did more testing in very simple scenario  wit phones no cluster, no dialog replication and B flag works on timer 30 sec as example I see BYE, but involve  dialog cluster replication B flag is not working.


<img width="898" alt="Screen Shot 2022-05-12 at 5 03 08 PM" src="https://user-images.githubusercontent.com/59034879/168167715-85733482-7acf-475e-a6f2-afc9abeef80e.png">


Config 

```

#### Dialog
loadmodule "dialog.so"
modparam("dialog", "db_url", "postgres://opensips:opensips123@127.0.0.1:5432/opensips")
modparam("dialog", "db_mode", 3)
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 3600)
modparam("dialog", "options_ping_interval", 900)
modparam("dialog", "profiles_with_value", "caller ; domain")

        if (is_method("INVITE")) {
                create_dialog("B");
                $DLG_timeout = 30;
                do_accounting("log");
        }

```

**Comment by volga629-1** [comment]
I did test with regular call, timer 30 and shared tag been set.
There are no BYE from opensips when timer expired.


```
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705375]: [DLG_SHARED_TAG] [INVITE] Set dialog tag vip1 ~> 8
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705375]: [MEDIA_IP] [INVITE] Set RTP instance => 2 with media IP =>  1.1.1.1
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705375]: [RTP_IS_SECURE] [INVITE] Extracted mline => RTP/AVP
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705375]: [RTP_MANAGE] [INVITE] Call going from WAN SouceIP <72.141.75.34> to LAN with media in-iface=external out-iface=internal
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705375]: [RELAY] [INVITE] sending call ~> $ru=sip:999@3cxdev.domain.com:5060;user=phone over udp:172.16.105.4:5060 for 1480107255401-406015657664539@72.141.75.34
May 13 06:33:02 devossbc01 /usr/sbin/opensips[1705363]: OnReply_Route3: [INVITE]  Direction: <null>  and source IP 10.5.25.116 with media => in-iface=internal out-iface=external #012                                    setid => 2 rtp transport => always-transcode RTP/AVP
```

**Comment by volga629-1** [comment]
I set unique tag for each call and state always **Backup**. what will be mechanism to set active on it ?



```
(opensips-cli): mi clusterer_list_shtags
[
    {
        "Tag": "csta-df57617d-1258-429a-8fbc-3efae28b5b55",
        "Cluster": 1,
        "State": "backup"
    },

```

**Comment by volga629-1** [comment]
Another observation  that Custer configuration  set to 

```
modparam("clusterer", "sharing_tag", "sbc3/1=active")

```

and state reports 


```

(opensips-cli): mi clusterer_list_shtags
[
    {
        "Tag": "sbc3",
        "Cluster": 1,
        "State": "backup"
    },
```

**Comment by razvancrainea** [comment]
@volga629-1 as you probably observed, when using sharing tags, only the node that has the tag active will send the BYE. You can set the tag as active using the `clusterer_shtag_set_active` MI command.
In this report I see that you make several observations, but tbh, I am not sure I find an issue here. Unless you have a node that has the tag active, and that does not send BYEs. If that is the case, please provide debugging logs for that call.

**Comment by volga629-1** [comment]
The issue I am set shared tag from on script level on initial csta INVITE and that tag always BACKUP and no buy is send ( expected ). 
That setup is active/active by default in cluster module param node set as active on all nodes.

**Comment by volga629-1** [comment]
> @volga629-1 as you probably observed, when using sharing tags, only the node that has the tag active will send the BYE. You can set the tag as active using the `clusterer_shtag_set_active` MI command.
> In this report I see that you make several observations, but tbh, I am not sure I find an issue here. Unless you have a node that has the tag active, and that does not send BYEs. If that is the case, please provide debugging logs for that call.

The issue that impossible set active state from script level, because  state always **BACKUP** when you set from scrip level .

**Comment by volga629-1** [comment]
I am just trying understand, what sense in this  if impossible change tag  state  and default behaviour is backup ?

```
1.7.21.  set_dlg_sharing_tag(tag_name)

Marks the current dialog with the sharing tag tag_name. From this point on, actions like in-dialog pinging, BYEs on timeout etc. will depend on the tag state(no action in "backup" state, normal operation in "active" state).


```

**Comment by volga629-1** [comment]
Hello @razvancrainea
Can you please provide you feedback ?

**Comment by volga629-1** [comment]
Hello @razvancrainea
Can you please provide you feedback ?

**Comment by volga629-1** [comment]
In progress

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
I created small lua  to set active state on shared tag to active on CSTA call there are still  issue where are flags are ignored   in create dialog  functions .


Shared tag 

```

        "Tag": "dlg-csta-097e85ef-7040-4de1-8aa0-a850770f98ac",
        "Cluster": 1,
        "State": "active"
    },

```



[CSTA-call-no-B-flag.txt](https://github.com/OpenSIPS/opensips/files/9253602/CSTA-call-no-B-flag.txt)


Configuration 

```

        # CSTA INVITE
        if(!has_totag() && is_method("INVITE") && has_body("application/csta+xml")) {
                if(sstCheckMin(1)) {
                        xlog("[REQ_ROUTE] [$rm] 422 Session Timer Too Small reply sent.\n");
                        exit;
                }
                # Track the session timers via the dialog module
                setflag("SST_FLAG");
                # Send BYE on dialog timeout
                create_dialog("B");
                # Dialog lifetime
                $DLG_timeout = 600;
                # shared tag
                route(DLG_SHARED_TAG);
                # Topology Hidding
                topology_hiding("U");
                #xlog("[REQ_ROUTE] [$rm] CSTA reqest from => [$socket_in(ip)]\n");
        }

```

**Comment by rvlad-patrascu** [comment]
Hi @volga629-1,

Firstly, I don't really see how an unique sharing tag per dialog would be useful in any dialog clustering scenario. They are not meant to be used this way. A sharing tag should be used to mark multiple dialogs(by VIP or node ID mostly, depending on the clustering scenario) and control which node should be "responsible" for that dialogs. Any new sharing tag starts in backup state if not otherwise defined through the clusterer modparam. And the only way the states transition after startup is by running that MI activate command which also forces the other nodes to step down to backup for that tag.

But as I understand, you are saying that BYEs are not SENT on dialog timeout even though the sharing tag of that dialog is active, right? Can you provide opensips debugging logs for such a dialog?

**Comment by volga629-1** [comment]
Hello @rvlad-patrascu Huge thank you for reply and patience. Yes, I can provide debug of such call,  because as you can see in attached file it is CSTA call not regular SIP call.
I set unique sharing tag, because of **active/active**  cluster where are  all nodes at same time get sip traffic from upstream sbc's, as you mention if not set it always backup and flags in create dialog function have no affect. I tested with lua script in active state and result the same, dialog is not terminates on lifetime ( that demonstrates in attached file, over 100 data exchange and then RE-INVITE and it can go for days like this).

Lua 


```
function tag_function(str)
        local tag = tostring(AVP_get("tag"))
        if tag ~= nil then
                xlog("Setting -> " .. tag .. " to active\n")
                local handle = io.popen("opensips-cli -x mi clusterer_shtag_set_active tag=".. tag .. '/' .. '1')
                local cmd_var = handle:read("*all")
                handle:close()
                xlog("Set active tag with result ~> " .. cmd_var .. "\n")
                return AVP_set("targrc", cmd_var)
	end
end

function getVersion()
    local handle = io.popen("hostname")
    xlog(_VERSION .. " runing on " .. handle:read("*all"))
end

```

**Comment by rvlad-patrascu** [comment]
For such an active-active setup, the most sense would make to have a sharing tag per node, and mark a dialog created on that node with the corresponding tag. Can you test with such a configuration?

**Comment by rvlad-patrascu** [comment]
Hi @volga629-1,

The sharing tag should be _per node_ not _per dialog_, i.e. you have 3 nodes -> 3 sharing tags.

**Comment by volga629-1** [comment]
Hello Vlad,
Thank you reply.
I tested with one tag per node and still no BYE on dialog time out for CSTA calls 

```
    {
        "Tag": "sbc1",
        "Cluster": 1,
        "State": "active"
    }

```
Side question.

If shared tag  not per dialog and cluster SBC1 fail, based on output of 

```
mi clusterer_list_shtags

```

will be no known dialogs  to other sbc nodes. All active calls even they relocated to other sbc's nodes will fail, because  no dialog data present.

Is I am missing something  ?

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
@rvlad-patrascu  I sent you email with information.

**Comment by volga629-1** [comment]
in

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in progress

**Comment by liviuchircu** [comment]
Hi, all!  I just went through this thread and I only have a few quick mentions ("safety checks" for @volga629-1):

1. make sure you have a _dialog cluster_ defined, so that dialogs are _mirrored_ to all "backup" nodes which can become "active" (in case of "active" SBC failure).  If you don't use dialog replication (e.g. keeping a hot backup node ready), there is _almost zero purpose_ in tagging dialogs to begin with.
2. the current best-practice is for the tags to start as `"backup"` (e.g. `modparam("clusterer", "sharing_tag", "sbc3/1=backup")`), then for external software to "fix" the tag to `"active"` on the correct node using the MI command.  This way, the setup does not break when flipping the traffic to the backup node and restarting the former-active node (its tag will no longer be incorrectly forced as `"active"` by the opensips.cfg).
3. as @rvlad-patrascu mentioned, on a normally functioning **N**-nodes active/active/active/.../active setup, you should have **N** sharing tags (e.g. `vip1`, `vip2`, ... , `vipN`).  And a `clusterer_list_shtags` command should produce `1` active tag and `N-1` backup tags _on each node_.

**Comment by volga629-1** [comment]
Thank you for reply, 
This setup active/active (MULTI HOMED TAGS on interfaces), on all nodes by default in cluster  mod param set as active on each node . 
Regard item 3 , Is on each dialog in script should be set shared tag ? If yes, I tried and I see as backup state. 

Confusion what happened with backup state if  cluster node goes offline, how other nodes will use it .
In my understand if replication send dialog info to other nodes in cluster all flags will be ignored, because of backup state of particular dialog. 

That what is my observation  were CSTA invite is dialog flags like B is ignored and no BYE on dialog time out variable.

Please

**Comment by liviuchircu** [comment]
> Regard item 3 , Is on each dialog in script should be set shared tag ? If yes, I tried and I see as backup state only
> 
> Confusion what happened with backup state if cluster node goes offline, how other nodes will use it . In my understand if replication send dialog info to other nodes in cluster all flags will be ignored, because of backup state of particular dialog.

Your Virtual IP solution (no matter if it's elastic IP, VRRP, BGP, etc.) **must** give you some callback where you can programmatically invoke the "cluster_shtag_set_active" MI command each time the VIP moves.  Unless you set this up correctly so the sharing tag moves along with the VIP, the "backup" dialogs (with "backup" tags) will be ignored, indeed.

If you do not currently have such a callback set up, please close this ticket, as it means the issue you are experiencing is configuration-related.

**Comment by volga629-1** [comment]
I am not using any VIP or any ip failover and that unrelated to this ticket. Original  issue that in CSTA call dialog flags ignored and there are no clear answer yet. volga629Sent from mobile device typos are expected.On Nov 3, 2022, at 06:40, Liviu Chircu ***@***.***> wrote:﻿

Regard item 3 , Is on each dialog in script should be set shared tag ? If yes, I tried and I see as backup state only
Confusion what happened with backup state if cluster node goes offline, how other nodes will use it . In my understand if replication send dialog info to other nodes in cluster all flags will be ignored, because of backup state of particular dialog.

Your Virtual IP solution (no matter if it's elastic IP, VRRP, BGP, etc.) must give you some callback where you can programmatically invoke the "cluster_shtag_set_active" MI command each time the VIP moves.  Unless you set this up correctly so the sharing tag moves along with the VIP, the "backup" dialogs (with "backup" tags) will be ignored, indeed.
If you do not currently have such a callback set up, please close this ticket, as it means the issue you are experiencing is configuration-related.

**Comment by volga629-1** [comment]
Right now in opensips script only set in cluster module param as active node total of 3 nodes. 
When CSTA call starts in script level invoked command create dialog with B flag and variable for dialog time out set to 4 min. Expectation on 4 min expire BYE will be send to leg A and B in order to close CSTA conversation correctly. Right now we use 481 to close late BYE.

**Comment by liviuchircu** [comment]
Wait, did you say you are doing this same thing on **all three nodes**?

```
modparam("clusterer", "sharing_tag", "sbc1/1=active")
modparam("clusterer", "sharing_tag", "sbc2/1=active")
modparam("clusterer", "sharing_tag", "sbc3/1=active")
```

If so, that is not the correct way to configure the tags - only **one** must be active at the same time.  The cluster will pick only 1 node to be "active" and will downgrade the other two as "backup", for each tag.

**Comment by volga629-1** [comment]
How about acctive/active setup, what you describing is active/passive. 
Each node contain copy of all dialogs. When one node down and call migrated to active node from fail node then active node knows exactly what is dialog status and process the call or CSTA call, by sending Re Invite.

**Comment by liviuchircu** [comment]
Vlad already described the active/active technique earlier in [this comment](https://github.com/OpenSIPS/opensips/issues/2829#issuecomment-1205336448), and then I re-iterated and described it **yet again** [in this comment](https://github.com/OpenSIPS/opensips/issues/2829#issuecomment-1300568456).  Please read everything once again, all information is already in this thread.

**Comment by volga629-1** [comment]
@rvlad-patrascu described active/active setup that need set tag per node. Is this only MI command or mod param ? In you table you describe active/passive that not active/active. Intention that active/active cluster can process calls from local dialog information and any node in cluster in case failure, that why need dialog replication.

**Comment by liviuchircu** [comment]
OK, we are on the right track.  This **is** an active/active setup, as each node is active for its own tag.  Correct?

Now, when SBC1 fails, you have some kind of callback (programmatic way of detecting this), so you **need** to send an MI command, and move the `sbc1` tag on SBC2, for example.  Does this make sense?

**Comment by volga629-1** [comment]
What is not clear, is tag per node, how you set it ?

**Comment by liviuchircu** [comment]
Here is an example for SBC1:

```
modparam("clusterer", "sharing_tag", "sbc1/1=active")
modparam("clusterer", "sharing_tag", "sbc1/1=backup")
modparam("clusterer", "sharing_tag", "sbc1/1=backup")

...

create_dialog("B");
set_dlg_sharing_tag("sbc1");
```

**Comment by volga629-1** [comment]
Let me try this configuration, but that really close what is configured, except  other nodes as backup.

**Comment by liviuchircu** [comment]
@volga629-1:  if you don't have a way (hook) to invoke `cluster_shtag_set_active` MI command, this solution will also not work.  Once you kill SBC1, the BYEs won't be _auto-magically_ sent by SBC2 without doing anything...

**Comment by volga629-1** [comment]
Yes, that correct for failover. Right now I am testing normal scenario , I want to see that B flag take affect first . Then I will check failover scenario . I have lua script  which monitor opensips process and if not answer it  will invoke MI command.

**Comment by volga629-1** [comment]
I did configuration changes and tested and no BYE on timeout in CSTA call.

Cluster


```
(opensips-cli): mi clusterer_list_shtags
[
    {
        "Tag": "sbc3",
        "Cluster": 1,
        "State": "backup"
    },
    {
        "Tag": "sbc2",
        "Cluster": 1,
        "State": "backup"
    },
    {
        "Tag": "sbc1",
        "Cluster": 1,
        "State": "active"
    }
]

```

Configuration

```

       # CSTA INVITE
        if(!has_totag() && is_method("INVITE") && has_body("application/csta+xml")) {
                if(sstCheckMin(1)) {
                        xlog("[REQ_ROUTE] [$rm] [$cfg_line] 422 Session Timer Too Small reply sent.\n");
                        exit;
                }
                #debug
                #$avp(debug) = "debug";
                #lua_exec("log_function", "$avp(debug)");
                #mi("log_level 4");
                xlog("[REQ_ROUTE] [$rm] [$cfg_line] CSTA reqest from => [$si] enabling debug\n");

                # Track the session timers via the dialog module
                setflag("SST_FLAG");
                # Send BYE on dialog timeout
                create_dialog("B");
                # Set low, testing
                $DLG_timeout = 90;
                # shared tag
                route(DLG_SHARED_TAG);
                # Topology Hidding
                topology_hiding("U");
                #xlog("[REQ_ROUTE] [$rm] [$cfg_line] CSTA reqest from => [$socket_in(ip)]\n");
        }
```

**Comment by volga629-1** [comment]
@liviuchircu  I sent you file with CSTA call.

**Comment by liviuchircu** [comment]
Remove your `dlg_set_sharing_tag()` call and redo the test.  You will see the "B" flag working.  If so, it means you are shooting yourself in the foot somehow, and mis-configuring your shared tags (which I suspect is happening).

**Comment by volga629-1** [comment]
Done test without dlg_set_sharing_tag() and same result no BYE,  although  dialog expired based on dialog var.


<img width="1330" alt="Screenshot 2022-11-03 at 3 41 04 PM" src="https://user-images.githubusercontent.com/59034879/199818770-730e05d0-cf3d-41a8-aad1-d49fcea275a1.png">

**Comment by liviuchircu** [comment]
For me, it works, @volga629-1, no matter what combination I try:

* with latest `3.2.9` or with your `3.2.4` from 10 months ago
* with sharing tag (active) or without sharing tag at all
* with `topology_hiding("U")` or without
* with no DB at all, or with `db_mode == 3` like in your setup

**Every time** (8/8 tries), OpenSIPS closes the call from the middle:

![it-works](https://user-images.githubusercontent.com/4446084/199830650-f61d41c5-7e99-433d-a603-c7adbf7a6a82.png)

Please check your script, as I noticed several Re-INVITEs happening in your SIP trace.  Maybe you are setting some weird `$DLG_timeout` in some route you don't expect.

Also, for the future, please provide a _minimally verifiable_ opensips.cfg file that reproduces the issue.

**Comment by volga629-1** [comment]
With normal SIP call works, but with CSTA no flags ignored. CSTA Re invites is resent by sip server when session timer expired.

**Comment by liviuchircu** [comment]
The 3CX system is sending these Re-INVITEs with SST headers:

```
Session-Expires: 600;refresher=uac
Min-SE: 90
```

... and I suspect you forgot you have loaded the `sst.so` module which is extending the lifetime of the dialog on each Re-INVITE from the 3CX, so the `"B"` flag is delayed for an extra `90` seconds on each Re-INVITE.

**Comment by volga629-1** [comment]
I tried both cases with session timer module in opensips and without. That true that possible to extend session, but it not changing fact that flags are ignored and no BYE, unless session timers enforces by server and opensips in middle have no influence on it.

**Comment by liviuchircu** [comment]
This is the way the `sst` module works:  by extending the lifetime by `+90`, the dialog won't time out when you set your initial, `$DLG_timeout`, as it will become `$DLG_timeout + 90`, then `$DLG_timeout + 180`, etc.  Please actually redo the test without `sst.so` module loaded and post the results.

**Comment by volga629-1** [comment]
Please confirm, the following configuration I am use  to reproduce the issue 
It include session timer.

```
        if(!has_totag() && is_method("INVITE") && has_body("application/csta+xml")) {
                if(sstCheckMin(1)) {
                        xlog("[REQ_ROUTE] [$rm] [$cfg_line] 422 Session Timer Too Small reply sent.\n");
                        exit;
                }
                #debug
                #$avp(debug) = "debug";
                #lua_exec("log_function", "$avp(debug)");
                #mi("log_level 4");
                xlog("[REQ_ROUTE] [$rm] [$cfg_line] CSTA reqest from => [$si] enabling debug\n");

                # Track the session timers via the dialog module
                setflag("SST_FLAG");
                # Send BYE on dialog timeout
                create_dialog("B");

                $DLG_timeout = 60;
                # shared tag
                #route(DLG_SHARED_TAG);
                # Topology Hidding
                topology_hiding("U");
                #xlog("[REQ_ROUTE] [$rm] [$cfg_line] CSTA reqest from => [$socket_in(ip)]\n");
        }

```

**Comment by liviuchircu** [comment]
I have nothing more to confirm, as you have just disabled the clustering support, and the issue is still there.  This means that the problem is no longer related to clustering support (or sharing tags) as per your initial theory, and is actually induced by SST Re-INVITEs from 3CX and the `sst.so` OpenSIPS module.

I am not going to do any SST tests, as the logic in the code is pretty obvious:  on every Re-INVITE, the DLG timeout gets bumped.  So this ticket is completed.

**Comment by volga629-1** [comment]
No cluster support in place and dialog replication is place.

                # shared tag
                #route(DLG_SHARED_TAG);

Shared tag been disabled  for testing.

The main question why  dialog flags is  ignored  and  dialog life timeout is ignored ?  Session timer is not enforced  by server, because  SST module in opensips set timer and 3CX answer request .  Is this should other way around where are dialog timeout supersede session timers ?

**Comment by liviuchircu** [comment]
> Also not clear how it related dialog life timers and session timers.

Taken from the [_official SST module documentation_](https://opensips.org/docs/modules/3.4.x/sst.html), 1st paragraph:

```
The sst module uses the dialog module to be notified of any new or updated dialogs. It will then look for and extract the session-expire: header value (if there is one) and override the dialog expire timer value for the current context dialog.
```

If you were to do a "no sst.so" test in a LAB environment (I understand you cannot remove `sst.so` in production), then you will see the `"B"` dialog flag working correctly.  For any issues around the behavior of SST module, please open a separate ticket.

There are no more issues to address in this ticket:  all of CSTA, cluster, shtags and active/active were false tracks which are all functioning correctly.

**Comment by volga629-1** [comment]
In production I can make changes as need, but dev is exact mirror of prod.
I don't think issue issue related to any timers, I think it just B flag ignored on CSTA call.

I disabled in dev session timer module completely, only left  dialog default timer.

```
modparam("dialog", "default_timeout", 240)
```

Plus dialog variable  +90 seconds

I see dialog expired, but no BYE  based on B flag.
Opensips replies 481, because I am checking for dialog state 5.

<img width="1169" alt="Screenshot 2022-11-04 at 11 54 28 AM" src="https://user-images.githubusercontent.com/59034879/200020027-d1bf0fe7-8e97-442f-b5a3-2761f0ba1cc5.png">

**Comment by liviuchircu** [comment]
* maybe you forgot to disable `set_dlg_sharing_tag()` and the tag is `backup`, per the initial setup
* maybe you forgot to comment random code with tag names per dialog (UUID), also with `backup` state, per the initial setup
* maybe there is _yet another_ thing I don't know about your script which is causing this behavior

I will only continue this ghost chase here if you provide a [_minimally reproducible example_](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of this issue.  This includes `sipp` test scenarios + `opensips.cfg` file for the middle proxy.

**Comment by volga629-1** [comment]
I  think the best way  is I can provide you access to dev , which already has 100% reproducible  environment  and original configuration files. Also full CSTA environment, I don't think with sipp you can generate CSTA call. And you check you self. I am pretty positive on all items you mention in list, that they disabled. 
I am testing on sbc1 which is active per my previous comments. 

```
(opensips-cli): mi clusterer_list_shtags
[
    {
        "Tag": "sbc3",
        "Cluster": 1,
        "State": "backup"
    },
    {
        "Tag": "sbc2",
        "Cluster": 1,
        "State": "backup"
    },
    {
        "Tag": "sbc1",
        "Cluster": 1,
        "State": "active"
    }
]
(opensips-cli):

**Comment by volga629-1** [comment]
I sent you files with two calls. One CSTA call  BYE is been sent to both participated  parties and another CSTA call where are  failing.
That point back to shared tag where are call with proper flow B flag is activated, because of node active state and another call right after seems like in back up state that why B is not active.
All this start shows after I disabled most timers.
I can't explain regard shared tag situation. Configuration is set right now as you pointed local node active and two remote backup.
