### ISSUE TITLE
[CRASH] b2b and rtp_relay: could not find logic tuple.

### ISSUE THREAD

**Issue by devoxy1** [OpenSIPS/opensips#3117]
Hello!

I experience intermittent crash on 3.4-beta version using b2b and rtp_relay modules. Opensips is configured as SBC and sometimes after restart opensips service and then making new call i get segfault. It looks like there is some old data kept in db for dialogs and it doesn't get cleaned up and then not processed correctly. If i keep process standby for sometime without any calls, next call will work with crash.
I get core dump for this everytime and the error in logs mentioning programming bug.

Here is my config part:
```
route(callrouting); #there are some drouting logic

if (!has_totag()) {
        b2b_server_new("caller",,$avp(extra_hdrs),$avp(extra_hdr_bodies));
        b2b_client_new("callee", "$ru",,,,$avp(b2b_hdrs),$avp(b2b_hdr_bodies));

        xlog("L_INFO","[$ci] [$rm] [ROUTE] RTP Relay Engage");
        $rtp_relay = "replace-origin replace-session-connection";
        $rtp_relay_peer = "replace-origin replace-session-connection";
        rtp_relay_engage("rtpengine",0);
        # initialize B2B session
        xlog("L_INFO","[$ci] [$rm] [ROUTE] B2B logic key: $b2b_logic.key");
        trace( "tid","B","sip");
        b2b_init_request("refer");

        exit;
    }
```

**OpenSIPS version you are running**

```
version: opensips 3.4.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 18504bc5a
main.c compiled on 08:33:48 Jun 15 2023 with gcc 9
```

**Crash Core Dump**
https://file.io/GuRfssRiXLdw

**Describe the traffic that generated the bug**
Just a simple call - INVITE to opensips.

**To Reproduce**

1. Start OpenSIPS
2. Make a call
3. Finish call and restart opensips serivce via systemctl
4. Once opensips is started make new call.
5. During INVITE process segfault occurs

**Relevant System Logs**

There is relevant line. Full log is uploaded along with crash

```   opensips[230366]: CRITICAL:b2b_logic:b2bl_ctx_get_tuple: #012>>> could not find logic tuple [14871.1]#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012 ```

**OS/environment information**
 - Operating System: Ubuntu 20.04.5 LTS
 - OpenSIPS installation: source
 - other relevant information:

**Additional context**
I created another crash report some time ago, it might be related or even be the same bug but since i'm not post created new one: https://github.com/OpenSIPS/opensips/issues/3058

**Comment by bogdan-iancu** [comment]
After restarting opensips, before doing any new call, could you run the [b2b_list](https://opensips.org/html/docs/modules/3.4.x/b2b_logic.html#mi_b2b_list)  and [b2be_list](https://opensips.org/html/docs/modules/3.4.x/b2b_entities.html#mi_b2be_list) MI cmds, just to check what is still memory?

**Comment by devoxy1** [comment]
Hello @bogdan-iancu,

Here is output of commands after restart:
```
opensips-cli -x mi b2b_list
{
    "Tuples": [
        {
            "id": 0,
            "key": "8600.0",
            "state": 0,
            "lifetime": 1,
            "db_flag": 1,
            "scenario": "refer",
            "SERVERS": [
                {
                    "index": 0,
                    "scenario_id": "caller",
                    "key": ".5451.6545.1687953369.755187080",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 0,
                    "peer": ".8600.6800429.1687953369.1360221935",
                    "to_uri": "sip:11111111111@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ],
            "CLIENTS": [
                {
                    "index": 0,
                    "scenario_id": "callee",
                    "key": ".8600.6800429.1687953369.1360221935",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 1,
                    "peer": ".5451.6545.1687953369.755187080",
                    "to_uri": "sip:11111111111@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ],
            "BRIDGE_ENTITIES": [
                {
                    "index": 0,
                    "scenario_id": "caller",
                    "key": ".5451.6545.1687953369.755187080",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 0,
                    "peer": ".8600.6800429.1687953369.1360221935",
                    "to_uri": "sip:11111111111@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                },
                {
                    "index": 1,
                    "scenario_id": "callee",
                    "key": ".8600.6800429.1687953369.1360221935",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 1,
                    "peer": ".5451.6545.1687953369.755187080",
                    "to_uri": "sip:11111111111@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ]
        },
        {
            "id": 1,
            "key": "14871.1",
            "state": 0,
            "lifetime": 1,
            "db_flag": 1,
            "scenario": "refer",
            "SERVERS": [
                {
                    "index": 0,
                    "scenario_id": "caller",
                    "key": ".9412.11999.1687953345.908622576",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 0,
                    "peer": ".14871.400969.1687953345.1577270512",
                    "to_uri": "sip:33333333333@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ],
            "CLIENTS": [
                {
                    "index": 0,
                    "scenario_id": "callee",
                    "key": ".14871.400969.1687953345.1577270512",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 1,
                    "peer": ".9412.11999.1687953345.908622576",
                    "to_uri": "sip:33333333333@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ],
            "BRIDGE_ENTITIES": [
                {
                    "index": 0,
                    "scenario_id": "caller",
                    "key": ".9412.11999.1687953345.908622576",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 0,
                    "peer": ".14871.400969.1687953345.1577270512",
                    "to_uri": "sip:33333333333@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                },
                {
                    "index": 1,
                    "scenario_id": "callee",
                    "key": ".14871.400969.1687953345.1577270512",
                    "disconnected": 0,
                    "state": 0,
                    "no": 0,
                    "type": 1,
                    "peer": ".9412.11999.1687953345.908622576",
                    "to_uri": "sip:33333333333@1.1.1.1",
                    "from_uri": "sip:2222@2.2.2.2"
                }
            ]
        }
    ]
}
```

```
opensips-cli -x mi b2be_list
[
    {
        "dlg": 6545,
        "logic_key": "8600.0",
        "mod_name": "b2b_logic",
        "state": 1,
        "last_invite_cseq": 16720,
        "last_method": 0,
        "db_flag": 0,
        "ruri": "sip:11111111111@3.3.3.3:5060",
        "callid": "34a3c6a7-c334-4f52-b646-1892be4e36b2",
        "from": "\"ChickenMan\"",
        "from_uri": "sip:2222@2.2.2.2",
        "from_tag": "0fd45976-6e0f-4682-a723-ebb0642dd3c8",
        "to": "",
        "to_uri": "sip:11111111111@3.3.3.3",
        "to_tag": ".5451.6545.1687953369.1569449201",
        "cseq": {
            "caller": 16720,
            "callee": 1
        },
        "contact": {
            "caller": "sip:asterisk@2.2.2.2:5060",
            "callee": "sip:3.3.3.3"
        },
        "send_sock": "3.3.3.3",
        "LEGS": [
            {
                "id": 0,
                "tag": "",
                "cseq": 1192324385,
                "contact": ""
            }
        ]
    }
]
```

**Comment by rvlad-patrascu** [comment]
Hi @devoxy1 ,

Can you please upload again the file(s) containing the crash backtrace/logs? https://file.io/GuRfssRiXLdw seems to have expired.

**Comment by devoxy1** [comment]
Hello @rvlad-patrascu,

Sure, here you go: https://file.io/dAYGSiBUfejS

**Comment by rvlad-patrascu** [comment]
Hi @devoxy1 ,

Can you please open the previous core file and print the following?

```
f 4
p *key
p local_ctx_tuple
p *local_ctx_tuple
p *local_ctx_tuple->key
```

This is just to confirm a related issue that contributed to the conditions for the crash to occur.

Nevertheless, I have pushed the fixes so you can re-test with the latest commits and the crash should be fixed.

**Comment by devoxy1** [comment]
> Hi @devoxy1 ,
> 
> Can you please open the previous core file and print the following?
> 
> ```
> f 4
> p *key
> p local_ctx_tuple
> p *local_ctx_tuple
> p *local_ctx_tuple->key
> ```
> 
> This is just to confirm a related issue that contributed to the conditions for the crash to occur.
> 
> Nevertheless, I have pushed the fixes so you can re-test with the latest commits and the crash should be fixed.

Hi @rvlad-patrascu!

Unfortunately old coredump seems to get lost, but i made new crash and collected bt full along with commands you mentioned. Please check out file here https://file.io/SfnFctA7yAyj
I hope this crash has the same root, i saved dump just incase.

Will do testing with fixes a bit later today and report.

**Comment by devoxy1** [comment]
@rvlad-patrascu,

I made test with new commit ebf40c91f and it b2b functionality stopped working. I make call, it is passed to b2b but no new leg is created, INVITE is not replied with 200OK, the call is hangup by remote side after 3 unanswered INVITEs. 
Please see full debug log here: https://file.io/yV1RchGpeJWj

It looks like it stops on these lines:
``` 
opensips[34526]: DBG:b2b_logic:get_ctx_tuple: b2b_logic key not set in b2b_entities context
opensips[34526]: DBG:b2b_logic:pv_get_b2bl_key: Unable to get the tuple from the current context
```

Reverting back to 3.4-beta fixes the issue without any other configuration or else changes.


```
version: opensips 3.4.0-rc1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ebf40c91f
main.c compiled on 11:45:57 Jul  5 2023 with gcc 9```

**Comment by rvlad-patrascu** [comment]
> I hope this crash has the same root, i saved dump just incase.

This crash has a different backtrace, it may still be related to our main issues here but I'm not sure at this point.

First thing to point out, https://github.com/OpenSIPS/opensips/commit/ebf40c91f9d62f367cddd722f05a1b53b6d30b6a is not the latest commit from the sequence I've pushed recently, you should test with https://github.com/OpenSIPS/opensips/commit/61401ea40f0394cbd589e3c3b301fa00e2aa05f6 or newer. But anyhow,  It's a bit strange that the basic b2b routing was broken by the latest commits since they should address a different part of the b2b functionalities.

> It looks like it stops on these lines:

Those line are to be expected if you are using in the script `$b2b_logic.key` or `$rtp_relay` and `$rtp_relay` before `b2b_init_request()`, since there is no b2b tuple created yet.

Can you post a longer sequence of the debug logs, maybe with some `xlog()` prints before and after  `b2b_init_request("refer");`? It looks like that function does not complete successfully but there are no ERR logs either.

Also it could be helpful if you could share from your opensips script, the entire main route and the b2b dedicated routes. You can send this to vladp@opensips.org if privacy is a concern.

**Comment by devoxy1** [comment]
> > I hope this crash has the same root, i saved dump just incase.
> 
> This crash has a different backtrace, it may still be related to our main issues here but I'm not sure at this point.
> 
> First thing to point out, [ebf40c9](https://github.com/OpenSIPS/opensips/commit/ebf40c91f9d62f367cddd722f05a1b53b6d30b6a) is not the latest commit from the sequence I've pushed recently, you should test with [61401ea](https://github.com/OpenSIPS/opensips/commit/61401ea40f0394cbd589e3c3b301fa00e2aa05f6) or newer. But anyhow, It's a bit strange that the basic b2b routing was broken by the latest commits since they should address a different part of the b2b functionalities.
> 
> > It looks like it stops on these lines:
> 
> Those line are to be expected if you are using in the script `$b2b_logic.key` or `$rtp_relay` and `$rtp_relay` before `b2b_init_request()`, since there is no b2b tuple created yet.
> 
> Can you post a longer sequence of the debug logs, maybe with some `xlog()` prints before and after `b2b_init_request("refer");`? It looks like that function does not complete successfully but there are no ERR logs either.
> 
> Also it could be helpful if you could share from your opensips script, the entire main route and the b2b dedicated routes. You can send this to [vladp@opensips.org](mailto:vladp@opensips.org) if privacy is a concern.

@rvlad-patrascu, 

I've recompiled commit eab713153 and made another test. Log level is 7, with new commit there is actually an error:
```
ERROR:rtp_relay:rtp_relay_dlg_req_callbacks: call engage after creating dialog!
```

I uploaded full log for failed (current commit) and successful(3.4-beta from source) calls and script file: https://file.io/Vqpm1r8DGda8

```
version: opensips 3.4.0-rc1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: eab713153
main.c compiled on 13:50:54 Jul  5 2023 with gcc 9
```

**Comment by rvlad-patrascu** [comment]
Hi @devoxy1 ,

Can you please test with this patch?
[b2b_logic_new_cb_deadlock.patch.txt](https://github.com/OpenSIPS/opensips/files/11962204/b2b_logic_new_cb_deadlock.patch.txt)

**Comment by devoxy1** [comment]
@rvlad-patrascu,
I applied patch but the issue is still the same:
`ERROR:rtp_relay:rtp_relay_dlg_req_callbacks: call engage after creating dialog!`

I'm not sure if used it right please let me know if there is another way.
I did `make clean` in the git folder, then `git patch b2b_logic_new_cb_deadlock.patch.txt` - I checked module files, changes seems to be applied and then recompiled.

**Comment by rvlad-patrascu** [comment]
@devoxy1 ,

If you see all the changes from the patch in the `git diff` output and then you do `make clean` and recompile, then it's probably ok.

The `ERROR:rtp_relay:rtp_relay_dlg_req_callbacks: call engage after creating dialog!` error might be related to a different issue than before. Is the basic b2b functionality and calling still not working? If so, can you post debug logs?

**Comment by devoxy1** [comment]
@rvlad-patrascu,
Sure, here is log https://file.io/SuQYJ5BmGm4Y with log level of 7.
Unfortunately since i can't make call with patch i can't check if the issue with crash is resolved.

**Comment by rvlad-patrascu** [comment]
Ok, there is some progress with this patch but it' still deadlocking somewhere. Can you also post the file produced by `opensips-cli -x trap`? You should run this command after a failed call.

**Comment by devoxy1** [comment]
@rvlad-patrascu  Done, please see file here: https://file.io/CsbxdyBzj2CC

**Comment by rvlad-patrascu** [comment]
Hi @devoxy1 ,

Found the new culprit. Can you please replace the previous patch with this new one?
[b2b_logic_api_deadlocks.patch.txt](https://github.com/OpenSIPS/opensips/files/12000155/b2b_logic_api_deadlocks.patch.txt)

**Comment by devoxy1** [comment]
Btw, the error still appears but rtp_relay puts correct addresses so i'm not sure if i should do anything with it.
`ERROR:rtp_relay:rtp_relay_b2b_tm_req: could not find a pending peer leg!`

**Comment by razvancrainea** [comment]
@devoxy1 can you please try to call `rtp_relay_engage` function in local route, see if the error still appears? Also, is the error triggered for every scenario?

**Comment by devoxy1** [comment]
Hello @razvancrainea,
 
If i put it in local_route, i get the error:
`Command <rtp_relay_engage> cannot be used in the block#012`
and opensips doesn't start because of bad config file.
Yes, it goes for every call for any scenario because b2b_init_request with rtp_relay goes for every call on my setup.

**Comment by devoxy1** [comment]
Hi @rvlad-patrascu!
I haven't experienced this issue so far, i think this can be closed.

Thank you!

**Comment by razvancrainea** [comment]
@devoxy1 closing the ticket then - if you're still experiencing errors, let's continue this on a different ticket, as it is not related to the initial error.
