### ISSUE TITLE
call_center crash

### ISSUE THREAD

**Issue by J0hnSteel** [OpenSIPS/opensips#984]
Hello yesterday I had a brief conversation with @razvancrainea razvanc on IRC about call_center and media announcements.
My issue is that when the agent is in wrap_up time and I initiate a call during that time I go to queue and moh starts playing , but when the call needs to be transferred to the agent opensips crashes and the caller is stuck in moh forever.
I'm using opensips 2.2 commit c8a605b, as a media server I'm using Asterisk 11.11.0 listening on port 5065 on the same host different ip.
core dump from the crash 

pastebin.com/raw/ApdzpAwM

**Comment by bogdan-iancu** [comment]
Hi @J0hnSteel , I see that the stat variable is not populated by the b2b module. Let me investigate and come back with a a fix.

**Comment by bogdan-iancu** [comment]
@J0hnSteel , do you have a pcap capture (from OpenSIPS) of the whole case (covering the call from user, the call to MOH, and call to agent) ? I just want to double check the triggering of the callbacks in b2b.
You can PM to me if you have sensitive info ;).

Thanks,
Bogdan

**Comment by J0hnSteel** [comment]
Hello @bogdan-iancu I went over my pcap files but didn't find a session containing the whole case. I'll generate one today and will send it to you by pm.

**Comment by bogdan-iancu** [comment]
thank you @J0hnSteel

**Comment by J0hnSteel** [comment]
Hey @bogdan-iancu I've sent you an email with the pcap file regarding this issue

**Comment by bogdan-iancu** [comment]
@J0hnSteel , I might have found the problem - a fix is available on trunk for testing. You can fetch the patch via https://github.com/OpenSIPS/opensips/commit/36b490858f9ae84a01ae4389915e3ae47b5b9119.diff .
Please test and let me know if the problem is fixed, so I can do official backports to the older versions.

Many thanks,
Bogdan

**Comment by J0hnSteel** [comment]
Hey @bogdan-iancu opensips is not crashing but now the agent gets stuck in wrapup time and wrapup is set to 15 sec. and inside opensips.log I see this 
Nov  9 12:26:06 debian-voip /sbin/opensips[2138]: WARNING:core:timer_ticker: timer task <cc_agents> already scheduled for 72280 ms (now 576750 ms), it may overlap..
and the part ***72280 ms (now 858320 ms), it may overlap..*** is growing to infinity without stopping continuously

**Comment by J0hnSteel** [comment]
Update that happens on the first call if I try to immediately place a second call if I let the first wrap up finish and a sucessfull second call this if what I get when I initiate the third call I get this 
note  timer task already scheduled is still persistent in the logs at this point 
![Image of callcenter](https://s16.postimg.org/uwiprsx5h/2016_11_09_12_39_04_471x391.png)

**Comment by bogdan-iancu** [comment]
My bad @J0hnSteel , I forgot to release some lock - please pull commit 5739b15 too.

Many thanks, Bogdan

**Comment by J0hnSteel** [comment]
Hello @bogdan-iancu I've compiled the last commit and I got a crash again but this time might not be opensips related.
Might be that libc.so it is a bit older version 2.13 or 2.12 don't remember. I tried compiling the latest one for testing but I'm facing with some difficulties right now. If it is  libc related I'll post when I get that part sorted.
Here is the coredump
```log
#0  0xb779c424 in __kernel_vsyscall ()
No symbol table info available.
#1  0xb763a941 in raise () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
No symbol table info available.
#2  0xb763dd72 in abort () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
No symbol table info available.
#3  0x08085e65 in sig_alarm_abort (signo=14) at main.c:412
        __FUNCTION__ = "sig_alarm_abort"
#4  <signal handler called>
No symbol table info available.
#5  0xb779c424 in __kernel_vsyscall ()
No symbol table info available.
#6  0xb76bd72c in sched_yield () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
No symbol table info available.
#7  0x081b3ae5 in get_lock (lock=0xb32012a8) at net/../mem/../fastlock.h:204
        i = 0
#8  __tcpconn_lifetime (force=<optimized out>) at net/net_tcp.c:1442
        c = <optimized out>
        fd = <optimized out>
        force = 1
        next = <optimized out>
        part = <optimized out>
#9  tcp_destroy () at net/net_tcp.c:1626
        part = <optimized out>
#10 0x080865fa in cleanup (show_status=show_status@entry=1) at main.c:320
        __FUNCTION__ = "cleanup"
#11 0x0808724f in handle_sigs () at main.c:520
        chld = <optimized out>
        chld_status = <optimized out>
        overall_status = 139
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#12 0x08060a7a in main_loop () at main.c:716
        startup_done = <optimized out>
        chd_rank = 19
#13 main (argc=11, argv=0xbfbbbda4) at main.c:1261
        cfg_stream = 0x9fe7008
        c = <optimized out>
        r = <optimized out>
        tmp = 0xbfbbcf8a ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x81e64d4 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 1789263755
        rfd = <optimized out>
        __FUNCTION__ = "main"
```

**Comment by bogdan-iancu** [comment]
@J0hnSteel , this crash/corefile was generated at shutdown , when opensips was stopping.
Check that you may have 2 corefile - one from the actual crash and one from the shutdown part.

If there is only one with name "core" , the first corefile may have been overwritten during the second crash - check here http://www.opensips.org/Documentation/TroubleShooting-Crash  on how to properly generate multiple corefiles.

**Comment by bogdan-iancu** [comment]
@J0hnSteel , do you have any updates in regards to this fix ?
